In [1]:
import numpy as np
import torch

# numpy

In [2]:


t=np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t: ', t.ndim )
print('Shape of t: ',t.shape)

Rank of t:  1
Shape of t:  (7,)


In [4]:
print('t[0] t[1] t[-1] = ',t[0],t[1],t[-1])
print('t[2:5] t[4:-1]  = ',t[2:5],t[4:-1])
print('t[:2] t[3:]     = ',t[:2],t[3:])

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


In [5]:
t=np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print('Rank of t: ', t.ndim )
print('Shape of t: ',t.shape)

Rank of t:  2
Shape of t:  (4, 3)


# PYTORCH

In [7]:


t=torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [8]:
print(t.dim())
print(t.size())
print(t[0],t[1],t[-1])
print(t[2:5],t[4:-1])
print(t[:2],t[3:])

1
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [9]:
t=torch.FloatTensor([[1.,2.,3.],
                     [4.,5.,6.],
                     [7.,8.,9.],
                     [10.,11.,12.]
                    ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim())
print(t.size()) #(batch size, dim)
print(t[:,1]) #헷갈림
print(t[:,1].size())
print(t[:,:-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### broadcasting => 실수 조심!

In [11]:
#Same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


### Vector + scalar -> broadcasting 사용

In [12]:
m1= torch.FloatTensor([[1,2]]) # |m1|=(1,,2)
m2=torch.FloatTensor([3]) # 3 -> [[3,3]]  /////  |m2|=(1,) -> (1,2)
print(m1+m2)

tensor([[4., 5.]])


In [14]:
#2 X 1 Vector + 1 X 2 Vector
m1 = torch.FloatTensor([[1,2]]) # |m1|=(1,2) -> (2,2)
m2 = torch.FloatTensor([[3],[4]]) # |m2|=(2,1) -> (2,2)
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


### Multiplication vs Matrix Multiplication
####  m1.mul(m2)        vs            m1.matmul(m2)

### Mean

In [29]:
#Can't use mean() on integers
#t=torch.LongTensor([1,2])

t=torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [17]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [18]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### sum

### Max and Argmax

#### t.max(dim=0) 하게 되면 t.max(dim=0)[0]에는 max가, [1]에는 argument 가 입력된다


# lab 1-2


### View(Reshape in numpy) => 원하는 형태로 텐서 모양을 바꿀 수 있음

In [23]:
t=np.array([[[0,1,2],
             [3,4,5]],
            
            [[6,7,8],
             [9,10,11]]])
ft=torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [24]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [25]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze

In [26]:
ft=torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [27]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])



### Unsqueeze

